name: Ultroid

on:

  push:

  workflow_dispatch:

jobs:

  userbot:

    runs-on: ubuntu-latest

    steps:

      - name: Running userbot in github action

        run: git clone https://github.com/rootedcyber93/Ultroid;cd Ultr*;pip3 install -r req*;pip3 install -r res*/st*/opt*;wget -O .env ${{ secrets.ENV }};bash startup
